#the database djdesweb must be created previously

services:
  dj_project_1:
    restart: "no"
    build: ./dj_project_1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dj_project_1:/usr/src/app
    ports:
      - ${DEVELOP_DOCKER_DJANGO_API_FORWARDED_PORT}:8000
    env_file:
      - .env
      - .env.dev
    networks:
      - postgis_postgis

networks:
   postgis_postgis:
      driver: bridge
      external: true

