# Generated by Django 5.0.6 on 2024-06-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deptos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_depto', models.CharField(max_length=30)),
                ('id_depto', models.IntegerField(unique=True)),
                ('n_mpios', models.IntegerField(null=True)),
                ('main_city', models.CharField(max_length=30)),
                ('date_create', models.DateTimeField()),
            ],
        ),
    ]
