# Generated by Django 5.0.6 on 2024-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_deptos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mpios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_mpio', models.CharField(max_length=30)),
                ('id_mpio', models.IntegerField(unique=True)),
                ('n_veredas', models.IntegerField(null=True)),
                ('cabecera', models.CharField(max_length=30)),
                ('date_create', models.DateTimeField()),
            ],
        ),
    ]
