# Generated by Django 5.0.6 on 2024-06-28 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_deptos_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptos',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
