# Generated by Django 5.0.6 on 2024-06-28 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_deptos_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deptos',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='deptos',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mpios',
            name='date_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='mpios',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
